general:
  seed: 42
  cuda_deterministic: true
  use_cuda: False

training:
  scheduling:
    batch_size: 16
    epoch: 10000
    model_checkpoint_path: 'saved_models/model1.pt'

  optimizer:
    learning_rate: 0.0001
    learning_rate_decay_ratio: 0.95
    learning_rate_decay_lowerbound: 0.01  # if lr < lowerbound * init_lr, then stop cutting
    learning_rate_decay_patience: 2
    clip_grad_norm: 5
